---
# tasks file for net
- name: Install Nginx
  apt: 
    name: nginx
    state: latest
 
- name: Install PHP-FPM
  apt: 
    name: php5-fpm
    state: latest

- name: Configure PHP
  lineinfile:
    dest: /etc/php5/fpm/php.ini
    regexp: ';cgi.fix_pathinfo=0'
    insertafter: 'cgi.fix_pathinfo'
    line: 'cgi.fix_pathinfo = 0'

- name: Edit Configuration file of Nginx
  template: 
    src: default_host.j2
    dest: /etc/nginx/sites-available/default

- name: Create Root Directory
  file: 
    path: /usr/share/nginx/html/
    state: directory

- name: Upload info.php
  template: 
    src: index.php.j2
    dest: /usr/share/nginx/html/phpinfo.php
    mode: 0755
